### ISSUE TITLE
Docs show incorrect values for 'Do Calculus' examples

### ISSUE THREAD

**Issue by Justice4Joffrey** [quantumblacklabs/causalnex#139] opened 2021-10-04 13:09 UTC
## Description
The documentation shows unchanged values after applying `.do_intervention()` in the following snippets:

https://causalnex.readthedocs.io/en/latest/03_tutorial/01_first_tutorial.html#Updating-a-Node-Distribution
https://causalnex.readthedocs.io/en/latest/03_tutorial/01_first_tutorial.html#Effect-of-Do-on-Marginals

e.g. 
```
distribution before do {'no': 0.10752688172043011, 'yes': 0.8924731182795698}
distribution after do {'no': 0.10752688172043011, 'yes': 0.8924731182795698}
```
should be more like -
```
distribution before do {'no': 0.10752688172043011, 'yes': 0.8924731182795698}
distribution after do {'no': 0.0, 'yes': 0.9999999999999998}
```

I've run locally and it appears to just be a display issue, rather than a problem with the method itself.

**Comment by oentaryorj** [comment] 2021-10-04 13:15
Thanks for reporting this. Hmmm ... this seems to be an HTML rendering problem, which I suspect may have something to do with `nbsphinx`. We will investigate further ...

**Comment by oentaryorj** [comment] 2021-10-15 11:24
This regression has been addressed in [this commit](https://github.com/quantumblacklabs/causalnex/commit/71bd1fb32b21cb5012cf8511b66c5ffb2e6e53cc), which is also now reflected in the [first tutorial](https://causalnex.readthedocs.io/en/latest/03_tutorial/01_first_tutorial.html).

**Closed by oentaryorj** 2021-10-15 11:24 UTC
Labels: documentation
